name: Maven Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean install

    - name: Test with Maven
      run: mvn clean test
